# Generated by Django 5.1.7 on 2025-03-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platforms',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
