# Generated by Django 5.1.7 on 2025-03-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gamelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='status',
            field=models.CharField(choices=[('played', 'Played'), ('abandoned', 'Abandoned'), ('shelved', 'Shelved'), ('completed', 'Completed'), ('wishlist', 'Wishlist')], default='played', max_length=20),
        ),
    ]
