# Generated by Django 5.1.7 on 2025-03-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gamelog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
    ]
