# Generated by Django 5.1.7 on 2025-03-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gamelog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelog',
            name='image',
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
    ]
