# Generated by Django 5.1.7 on 2025-03-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_gamelog_image_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='game_images/default_game.jpg', null=True, upload_to='game_images/'),
        ),
    ]
