# Generated by Django 5.1.7 on 2025-03-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_bio_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
